### PR TITLE
re-enable setting limits

### PR DESCRIPTION
**Pull request by SpheMakh**

### CODE REVIEW

**Comment by o-smirnov** [comment]
Ah, is this disabled in the current pip version? I've got some sims relying on this...

**Comment by SpheMakh** [comment]
I only had it disabled in the previous commit, the pip version was not affected.

**Comment by o-smirnov** [comment]
*phew*

**Comment by o-smirnov** [comment]
Hmmm maybe not *phew* -- my MSs have FLAG_ROW=True throughout. I was using ``-el 15``. Is it not in degrees? Computing elevation manually, I can see my source above 15deg.

**Pull request merged**
